# Generated by Django 5.1.4 on 2024-12-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0004_alter_members_email_alter_members_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(default='Email', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='fname',
            field=models.CharField(default='First Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='lname',
            field=models.CharField(default='Last Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='password',
            field=models.CharField(default='Password', max_length=50),
        ),
    ]
