# Generated by Django 5.1.4 on 2024-12-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0006_alter_members_email_alter_members_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePosters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
    ]
