# Generated by Django 5.1.4 on 2024-12-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0007_movieposters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoviePosters',
        ),
    ]
