# Generated by Django 5.1.4 on 2025-02-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0016_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
