# Generated by Django 5.1.4 on 2025-02-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0022_remove_upcoming_movie_upcoming_upcoming_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming',
            name='director',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
