# Generated by Django 5.1.4 on 2025-02-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0023_upcoming_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
