# Generated by Django 5.1.4 on 2025-02-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0024_upcoming_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
